

constexpr int SUBGRAPH_SIZE = 4;
constexpr int SEARCH_TREE_SIZE = 2000;
constexpr int MAX_SUBGRAPH_SIZE = 4;
constexpr int MAX_SUBGRAPH_SIZE_SQUARED = MAX_SUBGRAPH_SIZE* MAX_SUBGRAPH_SIZE;
constexpr long SUBGRAPH_INDEX_SIZE = 1 << MAX_SUBGRAPH_SIZE_SQUARED;

constexpr int RANDOM_GRAPH_NUMBER = 50;
